"""Initial schema for PostgreSQL

Revision ID: ceefc6047fdd
Revises: 
Create Date: 2026-07-15 09:34:19.752172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceefc6047fdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chat_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('member_ids', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_channels_project', 'chat_channels', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_channels_created_at'), 'chat_channels', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_channels_id'), 'chat_channels', ['id'], unique=False)
    op.create_index(op.f('ix_chat_channels_project_id'), 'chat_channels', ['project_id'], unique=False)
    op.create_table('de_building_benchmarks_2026',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gebaeudeart_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('gebaeudeart_de', sa.VARCHAR(length=120), nullable=False),
    sa.Column('gebaeudeart_fr', sa.VARCHAR(length=120), nullable=True),
    sa.Column('bgf_von_m2', sa.Integer(), nullable=True),
    sa.Column('bgf_bis_m2', sa.Integer(), nullable=True),
    sa.Column('kosten_pro_m2_basis', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kosten_min_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kosten_max_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kg_verteilung', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('typische_geschosse', sa.Integer(), nullable=True),
    sa.Column('typische_nutzung', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quelle', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gueltig_q', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_building_benchmarks_2026_gebaeudeart_code'), 'de_building_benchmarks_2026', ['gebaeudeart_code'], unique=False)
    op.create_table('de_labor_rates_2026',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gewerk_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('gewerk_de', sa.VARCHAR(length=120), nullable=False),
    sa.Column('gewerk_fr', sa.VARCHAR(length=120), nullable=True),
    sa.Column('gewerk_en', sa.VARCHAR(length=120), nullable=True),
    sa.Column('mindestlohn', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('lohn_helfer_w', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lohn_fach_w', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lohn_vorarbeiter_w', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lohn_polier_w', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lohn_fach_o', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lohn_polier_o', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('svs_west', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('svs_ost', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('svs_muenchen', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('svs_frankfurt', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('svs_berlin', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('jahresarbeitsstunden', sa.Integer(), nullable=False),
    sa.Column('tarifvertrag', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_labor_rates_2026_gewerk_code'), 'de_labor_rates_2026', ['gewerk_code'], unique=True)
    op.create_table('de_material_prices_2026',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('bezeichnung_de', sa.VARCHAR(length=200), nullable=False),
    sa.Column('bezeichnung_fr', sa.VARCHAR(length=200), nullable=True),
    sa.Column('kategorie', sa.VARCHAR(length=60), nullable=True),
    sa.Column('einheit', sa.VARCHAR(length=15), nullable=False),
    sa.Column('preis_basis', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preis_min', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('preis_max', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('lieferant_typ', sa.VARCHAR(length=50), nullable=True),
    sa.Column('co2_kg_per_unit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('recycling_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('din_en_norm', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gueltig_q', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_material_prices_2026_kategorie'), 'de_material_prices_2026', ['kategorie'], unique=False)
    op.create_index(op.f('ix_de_material_prices_2026_lieferant_typ'), 'de_material_prices_2026', ['lieferant_typ'], unique=False)
    op.create_index(op.f('ix_de_material_prices_2026_material_code'), 'de_material_prices_2026', ['material_code'], unique=True)
    op.create_table('de_price_index_2026',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('bezeichnung', sa.VARCHAR(length=200), nullable=False),
    sa.Column('basis_jahr', sa.Integer(), nullable=False),
    sa.Column('q1_2024', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q2_2024', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q3_2024', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q4_2024', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q1_2025', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q2_2025', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q3_2025', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q4_2025', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('q1_2026_est', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('jahres_aenderung_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quelle', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_price_index_2026_index_code'), 'de_price_index_2026', ['index_code'], unique=True)
    op.create_table('de_price_items_2026',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('stlb_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('bezeichnung_de', sa.VARCHAR(length=300), nullable=False),
    sa.Column('bezeichnung_fr', sa.VARCHAR(length=300), nullable=True),
    sa.Column('beschreibung_de', sa.Text(), nullable=True),
    sa.Column('kg_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('kg_label_de', sa.VARCHAR(length=120), nullable=True),
    sa.Column('kg_label_fr', sa.VARCHAR(length=120), nullable=True),
    sa.Column('gewerk_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('gewerk_de', sa.VARCHAR(length=120), nullable=True),
    sa.Column('ifc_entity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ifc_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('einheit', sa.VARCHAR(length=20), nullable=False),
    sa.Column('preis_basis', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preis_min', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('preis_max', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('material_anteil_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('lohn_anteil_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('geraet_anteil_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('co2_kg_per_unit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('recycling_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('din_norm', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gueltig_q', sa.VARCHAR(length=10), nullable=False),
    sa.Column('schwierigkeit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_price_items_2026_gewerk_code'), 'de_price_items_2026', ['gewerk_code'], unique=False)
    op.create_index(op.f('ix_de_price_items_2026_ifc_entity'), 'de_price_items_2026', ['ifc_entity'], unique=False)
    op.create_index(op.f('ix_de_price_items_2026_ifc_type'), 'de_price_items_2026', ['ifc_type'], unique=False)
    op.create_index(op.f('ix_de_price_items_2026_item_code'), 'de_price_items_2026', ['item_code'], unique=False)
    op.create_index(op.f('ix_de_price_items_2026_kg_code'), 'de_price_items_2026', ['kg_code'], unique=False)
    op.create_table('de_regions_2026',
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('bundesland', sa.VARCHAR(length=60), nullable=False),
    sa.Column('stadt', sa.VARCHAR(length=60), nullable=True),
    sa.Column('name_de', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name_fr', sa.VARCHAR(length=120), nullable=True),
    sa.Column('cost_index', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('lohn_index', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('material_index', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('einwohner', sa.Integer(), nullable=True),
    sa.Column('plz_bereich', sa.VARCHAR(length=50), nullable=True),
    sa.Column('markt_lage', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mietpreis_m2', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_de_regions_2026_bundesland'), 'de_regions_2026', ['bundesland'], unique=False)
    op.create_index(op.f('ix_de_regions_2026_markt_lage'), 'de_regions_2026', ['markt_lage'], unique=False)
    op.create_index(op.f('ix_de_regions_2026_tenant_id'), 'de_regions_2026', ['tenant_id'], unique=False)
    op.create_table('de_suppliers_2026',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('kategorie', sa.VARCHAR(length=60), nullable=True),
    sa.Column('region_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ort', sa.VARCHAR(length=120), nullable=True),
    sa.Column('plz', sa.VARCHAR(length=10), nullable=True),
    sa.Column('telefon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('web', sa.VARCHAR(length=300), nullable=True),
    sa.Column('lieferant_typ', sa.VARCHAR(length=50), nullable=True),
    sa.Column('material_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('zahlungsziel_tage', sa.Integer(), nullable=True),
    sa.Column('skonto_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('mindestbestellwert', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lieferradius_km', sa.Integer(), nullable=True),
    sa.Column('zertifizierungen', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('co2_reporting', sa.Boolean(), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('de_sustainability_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('epd_nummer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gwp_a1a3_kg_co2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gwp_a4_kg_co2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gwp_a5_kg_co2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gwp_b_kg_co2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gwp_c_kg_co2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gwp_d_kg_co2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ap_kg_so2e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ep_kg_po4e', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pop_kg_ethene', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('adpe_kg_sbe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('adpf_mj', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('duree_vie_ans', sa.Integer(), nullable=True),
    sa.Column('recyclable', sa.Boolean(), nullable=False),
    sa.Column('recyclage_pct_fin_vie', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('epd_verifieur', sa.VARCHAR(length=100), nullable=True),
    sa.Column('epd_valide_jusqu', sa.Date(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_sustainability_data_material_code'), 'de_sustainability_data', ['material_code'], unique=False)
    op.create_table('feedback_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('killer_feature', sa.String(), nullable=True),
    sa.Column('accuracy_rating', sa.String(), nullable=True),
    sa.Column('would_use_office', sa.String(), nullable=True),
    sa.Column('willingness_to_pay', sa.String(), nullable=True),
    sa.Column('missing_feature', sa.String(), nullable=True),
    sa.Column('voice_transcript', sa.String(), nullable=True),
    sa.Column('voice_backend', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_entries_id'), 'feedback_entries', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_entries_user_id'), 'feedback_entries', ['user_id'], unique=False)
    op.create_table('mood_checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('workload', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_checkins_id'), 'mood_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_mood_checkins_user_id'), 'mood_checkins', ['user_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('SOLO', 'AGENCY', 'ENTERPRISE', 'TRIAL', name='plantier'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('storage_quota_bytes', sa.Integer(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=True),
    sa.Column('max_team_members', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('has_advanced_analytics', sa.Boolean(), nullable=True),
    sa.Column('has_priority_support', sa.Boolean(), nullable=True),
    sa.Column('has_sso', sa.Boolean(), nullable=True),
    sa.Column('has_custom_branding', sa.Boolean(), nullable=True),
    sa.Column('price_monthly_cents', sa.Integer(), nullable=True),
    sa.Column('price_yearly_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_tier'), 'subscription_plans', ['tier'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('ak_member_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_migrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_author_created', 'chat_messages', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_chat_messages_channel_created', 'chat_messages', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_author_id'), 'chat_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_channel_id'), 'chat_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_client_id'), 'chat_messages', ['client_id'], unique=True)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('element_count', sa.Integer(), nullable=True),
    sa.Column('bgf', sa.Float(), nullable=True),
    sa.Column('bri', sa.Float(), nullable=True),
    sa.Column('ngf', sa.Float(), nullable=True),
    sa.Column('storey_count', sa.Integer(), nullable=True),
    sa.Column('location_plz', sa.String(), nullable=True),
    sa.Column('grossstadt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_tenant_id_id', 'projects', ['tenant_id', 'id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', 'PAUSED', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('external_subscription_id', sa.String(), nullable=True),
    sa.Column('payment_method_id', sa.String(), nullable=True),
    sa.Column('storage_quota_override_bytes', sa.Integer(), nullable=True),
    sa.Column('max_projects_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_plan', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_subscriptions_tenant_status', 'subscriptions', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_external_subscription_id'), 'subscriptions', ['external_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('cost_estimations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('gebaeudeart', sa.String(), nullable=True),
    sa.Column('standard', sa.String(), nullable=True),
    sa.Column('regional_faktor', sa.Float(), nullable=True),
    sa.Column('index_faktor', sa.Float(), nullable=True),
    sa.Column('total_netto', sa.Float(), nullable=False),
    sa.Column('total_brutto', sa.Float(), nullable=False),
    sa.Column('cost_per_m2_bgf', sa.Float(), nullable=False),
    sa.Column('confidence_low_80', sa.Float(), nullable=False),
    sa.Column('confidence_high_80', sa.Float(), nullable=False),
    sa.Column('co2_total_kg', sa.Float(), nullable=True),
    sa.Column('co2_per_m2', sa.Float(), nullable=True),
    sa.Column('geg_conform', sa.Boolean(), nullable=True),
    sa.Column('hoai_honorar_netto', sa.Float(), nullable=True),
    sa.Column('kg_breakdown', sa.JSON(), nullable=False),
    sa.Column('audit_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_estimations_tenant_id_id', 'cost_estimations', ['tenant_id', 'id'], unique=False)
    op.create_index(op.f('ix_cost_estimations_id'), 'cost_estimations', ['id'], unique=False)
    op.create_index(op.f('ix_cost_estimations_project_id'), 'cost_estimations', ['project_id'], unique=False)
    op.create_index(op.f('ix_cost_estimations_tenant_id'), 'cost_estimations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_estimations_tenant_id'), table_name='cost_estimations')
    op.drop_index(op.f('ix_cost_estimations_project_id'), table_name='cost_estimations')
    op.drop_index(op.f('ix_cost_estimations_id'), table_name='cost_estimations')
    op.drop_index('idx_cost_estimations_tenant_id_id', table_name='cost_estimations')
    op.drop_table('cost_estimations')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_subscription_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_tenant_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_plan', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index('idx_projects_tenant_id_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_client_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_channel_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_author_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_channel_created', table_name='chat_messages')
    op.drop_index('idx_chat_messages_author_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_tier'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_mood_checkins_user_id'), table_name='mood_checkins')
    op.drop_index(op.f('ix_mood_checkins_id'), table_name='mood_checkins')
    op.drop_table('mood_checkins')
    op.drop_index(op.f('ix_feedback_entries_user_id'), table_name='feedback_entries')
    op.drop_index(op.f('ix_feedback_entries_id'), table_name='feedback_entries')
    op.drop_table('feedback_entries')
    op.drop_index(op.f('ix_de_sustainability_data_material_code'), table_name='de_sustainability_data')
    op.drop_table('de_sustainability_data')
    op.drop_table('de_suppliers_2026')
    op.drop_index(op.f('ix_de_regions_2026_tenant_id'), table_name='de_regions_2026')
    op.drop_index(op.f('ix_de_regions_2026_markt_lage'), table_name='de_regions_2026')
    op.drop_index(op.f('ix_de_regions_2026_bundesland'), table_name='de_regions_2026')
    op.drop_table('de_regions_2026')
    op.drop_index(op.f('ix_de_price_items_2026_kg_code'), table_name='de_price_items_2026')
    op.drop_index(op.f('ix_de_price_items_2026_item_code'), table_name='de_price_items_2026')
    op.drop_index(op.f('ix_de_price_items_2026_ifc_type'), table_name='de_price_items_2026')
    op.drop_index(op.f('ix_de_price_items_2026_ifc_entity'), table_name='de_price_items_2026')
    op.drop_index(op.f('ix_de_price_items_2026_gewerk_code'), table_name='de_price_items_2026')
    op.drop_table('de_price_items_2026')
    op.drop_index(op.f('ix_de_price_index_2026_index_code'), table_name='de_price_index_2026')
    op.drop_table('de_price_index_2026')
    op.drop_index(op.f('ix_de_material_prices_2026_material_code'), table_name='de_material_prices_2026')
    op.drop_index(op.f('ix_de_material_prices_2026_lieferant_typ'), table_name='de_material_prices_2026')
    op.drop_index(op.f('ix_de_material_prices_2026_kategorie'), table_name='de_material_prices_2026')
    op.drop_table('de_material_prices_2026')
    op.drop_index(op.f('ix_de_labor_rates_2026_gewerk_code'), table_name='de_labor_rates_2026')
    op.drop_table('de_labor_rates_2026')
    op.drop_index(op.f('ix_de_building_benchmarks_2026_gebaeudeart_code'), table_name='de_building_benchmarks_2026')
    op.drop_table('de_building_benchmarks_2026')
    op.drop_index(op.f('ix_chat_channels_project_id'), table_name='chat_channels')
    op.drop_index(op.f('ix_chat_channels_id'), table_name='chat_channels')
    op.drop_index(op.f('ix_chat_channels_created_at'), table_name='chat_channels')
    op.drop_index('idx_chat_channels_project', table_name='chat_channels')
    op.drop_table('chat_channels')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
